### ISSUE TITLE
dashboard编辑流控规则页面bug

### ISSUE THREAD

**Issue by tfdxl** [alibaba/Sentinel#334] opened 2018-12-25 03:13 UTC
## Issue Description

*bug report* 

### Describe what happened (or what feature you want)

bug位置：流控规则-编辑流控规则页面

### Describe what you expected to happen

点击编辑按钮，修改单机阈值，关闭弹框，不保存，列表页的单机阈值被修改了。

### How to reproduce it (as minimally and precisely as possible)

1. 编辑页面的对象和列表页不要公用

### Tell us your environment

sentinel-dashboard-1.4.0.jar

**Comment by Tank-zhu** [comment] 2018-12-25 07:43
这里不是BUG呢。是如果你没有开启集群配置。就默认是单机呢。所以改了单机的。

**Comment by sczyh30** [comment] 2018-12-26 04:34
Duplicate of #95. We'll fix it later.

**Closed** 2018-12-27 07:47 UTC
Labels: duplicate
