### ISSUE TITLE
Sentinel 和 Feign 集成时，方法名称写错

### ISSUE THREAD

**Issue by dsaewq321** [alibaba/Sentinel#1345] opened 2020-03-18 14:20 UTC
版本：spring-cloud-alibaba-2.1.0.RELEASE

Sentinel 和 Feign 集成时，方法名称写错，有如下接口：
`List<MethodMetadata> feign.Contract.parseAndValidateMetadata(Class<?> targetType);`

在  spring-cloud-alibaba-sentinel-2.1.0.RELEASE.jar 中，实现了上述方法，不过方法名却写错了，导致目前无法使用，实现方法如下：
`List<MethodMetadata> com.alibaba.cloud.sentinel.feign.SentinelContractHolder.parseAndValidatateMetadata(Class<?> targetType);`

**Comment by sczyh30** [comment] 2020-03-18 14:22
Could you please provide the detailed error message?

**Comment by carCV** [comment] 2020-03-18 14:47
当我在集成 Sentinel 和 Feign 时，运行github上的示例代码，代码地址如下：
https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/java/com/alibaba/cloud/examples/controller/TestController.java

遇到了类似于上述的问题，具体问题日志如下：
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'echoController': Unsatisfied dependency expressed through field 'echoService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.jmlee.hello.sentinel.feign.service.EchoService': FactoryBean threw exception on object creation; nested exception is java.lang.AbstractMethodError: **com.alibaba.cloud.sentinel.feign.SentinelContractHolder.parseAndValidateMetadata(Ljava/lang/Class;)Ljava/util/List**;

### 所用版本：
Spring Cloud Version：Hoxton.SR3
Spring Cloud Alibaba Version：2.2.0.RELEASE

**Comment by sczyh30** [comment] 2020-03-18 15:26
@fangjian0423 Could you please take a look?

**Comment by Pointerv** [comment] 2020-03-20 06:25
Hoxton.SR1 中，fegin.context接口的定义为parseAndValidatateMetadata
Hoxton.SR3 中，fegin.context接口的定义为parseAndValidateMetadata。就是之前版本中定义的方法名拼写错误，所以在Hoxton.SR1后面的版本更正过来，所以出现Caused by: java.lang.AbstractMethodError: com.alibaba.cloud.sentinel.feign.SentinelContractHolder.parseAndValidateMetadata(Ljava/lang/Class;)Ljava/util/List;错误。

我目前的解决办法是：在工程合适的地方，新建包com.alibaba.cloud.sentinel.feign。重新修改一下SentinelContractHolder即可
`public class SentinelContractHolder implements Contract {

	private final Contract delegate;

	/**
	 * map key is constructed by ClassFullName + configKey. configKey is constructed by
	 * {@link feign.Feign#configKey}
	 */
	public final static Map<String, MethodMetadata> METADATA_MAP = new HashMap<>();

	public SentinelContractHolder(Contract delegate) {
		this.delegate = delegate;
	}

	@Override
	public List<MethodMetadata> parseAndValidateMetadata(Class<?> targetType) {
		List<MethodMetadata> metadatas = delegate.parseAndValidateMetadata(targetType);
		metadatas.forEach(metadata -> METADATA_MAP
				.put(targetType.getName() + metadata.configKey(), metadata));
		return metadatas;
	}
}`

**Comment by cdfive** [comment] 2020-03-20 16:15
By reproducing it, I found two ways to solve this:

1. Change Spring Cloud Version from `Hoxton.SR3` to `Hoxton.RELEASE`

2. Remain using `Hoxton.SR3`, and specified the version of `spring-cloud-openfeign-dependencies`
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-openfeign-dependencies</artifactId>
            <version>${spring-cloud-openfeign.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Hoxton.SR3</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-dependencies</artifactId>
            <version>2.2.0.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

Note that the `spring-cloud-openfeign-dependencies` should be in front of `spring-cloud-dependencies`.

The reason is as @Pointerv described.

**Comment by dsaewq321** [comment] 2020-03-21 01:15
对，我目前也是这样解决的。thanks.
&nbsp;


半缘&nbsp;忘忧
jens.wu@foxmail.com

exgwbvdtcfqpbgce


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Felix"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 下午2:26
收件人: "alibaba/Sentinel"<Sentinel@noreply.github.com&gt;; 
抄送: "半缘 忘忧"<329505775@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/Sentinel] Sentinel 和 Feign 集成时，方法名称写错 (#1345)





 
Hoxton.SR1 中，fegin.context接口的定义为parseAndValidatateMetadata
 Hoxton.SR3 中，fegin.context接口的定义为parseAndValidateMetadata。就是之前版本中定义的方法名拼写错误，所以在Hoxton.SR1后面的版本更正过来，所以出现Caused by: java.lang.AbstractMethodError: com.alibaba.cloud.sentinel.feign.SentinelContractHolder.parseAndValidateMetadata(Ljava/lang/Class;)Ljava/util/List;错误。
 
我目前的解决办法是：在工程合适的地方，新建包com.alibaba.cloud.sentinel.feign。重新修改一下SentinelContractHolder即可
 `public class SentinelContractHolder implements Contract {
 private final Contract delegate; /**  * map key is constructed by ClassFullName + configKey. configKey is constructed by  * {@link feign.Feign#configKey}  */ public final static Map<String, MethodMetadata&gt; METADATA_MAP = new HashMap<&gt;(); public SentinelContractHolder(Contract delegate) { 	this.delegate = delegate; } @Override public List<MethodMetadata&gt; parseAndValidateMetadata(Class<?&gt; targetType) { 	List<MethodMetadata&gt; metadatas = delegate.parseAndValidateMetadata(targetType); 	metadatas.forEach(metadata -&gt; METADATA_MAP 			.put(targetType.getName() + metadata.configKey(), metadata)); 	return metadatas; }  
}`

**Comment by dsaewq321** [comment] 2020-03-21 01:28
good idea, thank u&nbsp;
&nbsp;


半缘&nbsp;忘忧
jens.wu@foxmail.com

exgwbvdtcfqpbgce


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cdfive"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 凌晨0:15
收件人: "alibaba/Sentinel"<Sentinel@noreply.github.com&gt;; 
抄送: "半缘 忘忧"<329505775@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/Sentinel] Sentinel 和 Feign 集成时，方法名称写错 (#1345)





 
By reproducing it, I found two ways to solve this:
  
 
Change Spring Cloud Version from Hoxton.SR3 to Hoxton.RELEASE
 
 
 
Remain using Hoxton.SR3, and specified the version of spring-cloud-openfeign-dependencies
 
  <dependencyManagement&gt;     <dependencies&gt;         <dependency&gt;             <groupId&gt;org.springframework.cloud</groupId&gt;             <artifactId&gt;spring-cloud-openfeign-dependencies</artifactId&gt;             <version&gt;${spring-cloud-openfeign.version}</version&gt;             <type&gt;pom</type&gt;             <scope&gt;import</scope&gt;         </dependency&gt;         <dependency&gt;             <groupId&gt;org.springframework.cloud</groupId&gt;             <artifactId&gt;spring-cloud-dependencies</artifactId&gt;             <version&gt;Hoxton.SR3</version&gt;             <type&gt;pom</type&gt;             <scope&gt;import</scope&gt;         </dependency&gt;         <dependency&gt;             <groupId&gt;com.alibaba.cloud</groupId&gt;             <artifactId&gt;spring-cloud-alibaba-dependencies</artifactId&gt;             <version&gt;2.2.0.RELEASE</version&gt;             <type&gt;pom</type&gt;             <scope&gt;import</scope&gt;         </dependency&gt;     </dependencies&gt; </dependencyManagement&gt;
 
Note that the spring-cloud-openfeign-dependencies should be in front of spring-cloud-dependencies.
 
The reason is as @Pointerv described.

**Comment by fanqisoft** [comment] 2020-03-24 10:37
碰到了相同的问题，谢谢

**Comment by stalary** [comment] 2020-03-24 15:29
碰到了同样的问题，多谢

**Comment by fangjian0423** [comment] 2020-03-25 02:02
Spring Cloud Alibaba 2.2.0.RELEASE based on Hoxton.RELEASE.

Spring Cloud Alibaba 2.2.1.RELEASE based on Hoxton.SR3 and it's going to release soon.

**Comment by sczyh30** [comment] 2020-04-17 09:05
Closing this issue as SCA 2.2.1.RELEASE has been released. Thanks all :)

**Closed by sczyh30** 2020-04-17 09:05 UTC
Labels: integration/spring-cloud

**Comment by MemoryF** [comment] 2020-05-13 16:49
Caused by: java.lang.AbstractMethodError: com.alibaba.cloud.sentinel.feign.SentinelContractHolder.parseAndValidatateMetadata(Ljava/lang/Class;)Ljava/util/List;
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:154) ~[feign-core-10.4.0.jar:na]
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:52) ~[feign-core-10.4.0.jar:na]
	at feign.Feign$Builder.target(Feign.java:251) ~[feign-core-10.4.0.jar:na]
	at org.springframework.cloud.openfeign.HystrixTargeter.target(HystrixTargeter.java:38) ~[spring-cloud-openfeign-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:243) ~[spring-cloud-openfeign-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:272) ~[spring-cloud-openfeign-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:252) ~[spring-cloud-openfeign-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 48 common frames omitted




Caused by: java.lang.AbstractMethodError: com.alibaba.cloud.sentinel.feign.SentinelContractHolder.parseAndValidatateMetadata(Ljava/lang/Class;)Ljava/util/List;
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:154) ~[feign-core-10.4.0.jar:na]
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:52) ~[feign-core-10.4.0.jar:na]
	at feign.Feign$Builder.target(Feign.java:251) ~[feign-core-10.4.0.jar:na]
	at org.springframework.cloud.openfeign.HystrixTargeter.target(HystrixTargeter.java:38) ~[spring-cloud-openfeign-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:243) ~[spring-cloud-openfeign-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:272) ~[spring-cloud-openfeign-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:252) ~[spring-cloud-openfeign-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 48 common frames omitted

**Comment by MemoryF** [comment] 2020-05-13 17:01
2.2.1.RELEASE  Hoxton.SR3  可以适配了。但是要去中央仓库下载Hoxton.SR3  阿里云仓库还没有
